target 'HolyWaterTT' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'SnapKit', '~> 5.6.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

end
